name: Custom-action
description: echo test

inputs:
  path_dockerfile:
    description: "Allows to target the correct Dockerfile"
    required: false
    default: "Dockerfile"
  image_name:
    description: "Specifies the name for the generated Docker image"
    required: true
  tag_name:
    description: "Specifies the tag to be added to the final image"
    required: false

runs:
  using: composite
  steps:
    - run: |
        if [ -z "${{ inputs.tag_name }}" ]; then
            export TAG=$(date +%s)
        else
            export TAG="${{ inputs.tag_name }}"
        fi

        docker build . --file "${{ inputs.path_dockerfile }}" --tag "${{ inputs.image_name }}:${TAG}"
      shell: bash
